"use client";

import { useMemo, useState } from "react";
import { analyzeTownHallDecision } from "@/features/town-hall-decision/town-hall-decision.engine";
import type { TownHallDecisionInput, TownHallVariant } from "@/features/town-hall-decision/town-hall-decision.types";
import { strategyLabels, strategyLabelsEnglish } from "@/features/planning-control/planning-control";

type Props = { input: Omit<TownHallDecisionInput, "scheduledAt">; language: "de" | "en"; onCreateScenario: (variant: TownHallVariant, scheduledAt: string | null) => void };
const recommendations = { not_recommended: { de: "noch nicht empfohlen", en: "not recommended yet" }, possible: { de: "grundsätzlich möglich", en: "generally possible" }, recommended: { de: "empfohlen", en: "recommended" }, urgent: { de: "dringend sinnvoll", en: "strongly advisable" }, strategy_dependent: { de: "strategisch abhängig", en: "strategy-dependent" } };
const number = (value: number, en: boolean) => new Intl.NumberFormat(en ? "en-US" : "de-DE", { maximumFractionDigits: 1 }).format(value);

export function TownHallDecisionCard({ input, language, onCreateScenario }: Props) {
  const en = language === "en"; const [scheduledAt, setScheduledAt] = useState(() => new Date(Date.now() + 14 * 86_400_000).toISOString());
  const analysis = useMemo(() => analyzeTownHallDecision({ ...input, scheduledAt }), [input, scheduledAt]); const decision = analysis.decision;
  return <section className="rounded-3xl border border-emerald-300/20 bg-emerald-300/5 p-5 md:p-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-emerald-300">{en ? "Town Hall decision" : "Rathaus-Entscheidung"}</p><h2 className="mt-2 text-2xl font-bold">{en ? "Town Hall change" : "Rathauswechsel"}: {recommendations[decision.recommendation][language]}</h2><p className="mt-2 text-sm text-slate-300">{en ? "Personal score" : "Persönlicher Score"}: <b>{decision.score}/100</b> · Confidence <b>{decision.confidence}%</b> · {(en ? strategyLabelsEnglish : strategyLabels)[decision.strategy]}</p></div><div className="rounded-2xl bg-slate-950/70 px-5 py-4 text-center"><p className="text-xs text-slate-400">{en ? "Next Town Hall" : "Nächstes Rathaus"}</p><p className="text-2xl font-bold text-emerald-200">{decision.nextTownHallLevel ? `TH ${decision.nextTownHallLevel}` : "–"}</p></div></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-emerald-300/10 p-4"><h3 className="font-bold text-emerald-200">{en ? "What supports the change" : "Dafür spricht"}</h3><ul className="mt-3 space-y-2 text-sm">{decision.positives.length ? decision.positives.map((item) => <li key={item.code}>+ {en ? item.en : item.de}</li>) : <li className="text-slate-500">–</li>}</ul></div><div className="rounded-2xl bg-rose-300/10 p-4"><h3 className="font-bold text-rose-200">{en ? "What argues against it" : "Dagegen spricht"}</h3><ul className="mt-3 space-y-2 text-sm">{decision.negatives.map((item) => <li key={item.code}>– {en ? item.en : item.de}</li>)}</ul></div></div>
    <div className="mt-5 rounded-2xl bg-slate-950/60 p-4"><p className="text-sm"><b>{en ? "Recommendation" : "Empfehlung"}:</b> {decision.recommendation === "strategy_dependent" ? (en ? "Your areas differ strongly. The right timing depends on whether your current strategy values faster unlocks more than closing the displayed gaps." : "Deine Bereiche liegen deutlich auseinander. Der richtige Zeitpunkt hängt davon ab, ob deine Strategie schnellere Freischaltungen höher bewertet als das Schließen der angezeigten Lücken.") : decision.score >= 64 ? (en ? "The change fits your selected strategy; compare the variants below before adopting it." : "Der Wechsel passt zu deiner gewählten Strategie; vergleiche vor der Übernahme die Varianten unten.") : (en ? "Close the listed gaps or change the strategic assumptions before upgrading." : "Schließe zuerst die genannten Lücken oder ändere bewusst die strategischen Annahmen.")}</p>{decision.missingData.length ? <p className="mt-2 text-xs text-amber-200">{en ? "Confidence reduced by missing data" : "Confidence wegen fehlender Daten reduziert"}: {decision.missingData.join(", ")}</p> : null}</div>
    <div className="mt-6 flex flex-wrap items-end gap-3"><label className="text-xs text-slate-400">{en ? "Scheduled variant date" : "Datum der späteren Variante"}<input type="datetime-local" value={scheduledAt.slice(0,16)} onChange={(event) => setScheduledAt(event.target.value ? new Date(event.target.value).toISOString() : new Date().toISOString())} className="mt-1 block rounded-xl border border-white/10 bg-slate-950 p-3 text-white" /></label></div>
    <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-xs text-slate-400"><tr><th className="p-3">{en ? "Variant" : "Variante"}</th><th>{en ? "Total time" : "Gesamtdauer"}</th><th>{en ? "Resources" : "Ressourcen"}</th><th>{en ? "Heroes" : "Helden"}</th><th>{en ? "Offense" : "Offensive"}</th><th>{en ? "Rush risk" : "Rush-Risiko"}</th><th>{en ? "Goals" : "Ziele"}</th><th></th></tr></thead><tbody>{analysis.variants.map((variant) => <tr key={variant.id} className="border-t border-white/10"><td className="p-3 font-bold">{en ? variant.nameEn : variant.nameDe} *</td><td>{number(variant.totalDurationHours / 24, en)} {en ? "days" : "Tage"}</td><td>{number(Object.values(variant.resourcesRequired).reduce((a,b)=>a+b,0), en)}</td><td>{variant.heroProgress}%</td><td>{variant.offenseProgress}%</td><td>{variant.rushRisk}%</td><td>{variant.goalsAchievable ? "✓" : "!"}</td><td className="p-2"><button type="button" onClick={() => onCreateScenario(variant, variant.id === "upgrade_scheduled" ? scheduledAt : null)} className="rounded-xl border border-emerald-300/30 px-3 py-2 text-xs font-bold text-emerald-200">{en ? "Create scenario" : "Szenario anlegen"}</button></td></tr>)}</tbody></table></div>
    <p className="mt-3 text-xs text-slate-500">* {en ? "Model estimate using the isolated scenario engine. No account data is changed." : "Modellschätzung mit der isolierten Szenario-Engine. Es werden keine Accountdaten verändert."} · {decision.calculationVersion}</p>
  </section>;
}
