import assert from "node:assert/strict";
import test from "node:test";
import { analyzeTownHallDecision } from "@/features/town-hall-decision/town-hall-decision.engine";
import type { AccountHealthResult } from "@/features/account-health/account-health.types";
import type { ScenarioEvaluationContext } from "@/features/planning-scenarios/planning-scenario.engine";

const context: ScenarioEvaluationContext = { accountId: "a", townHallLevel: 16, builderCount: 5, plannerResult: { accountId: "a", accountName: "A", buildingProgress: [], possibleUpgrades: [], blockedUpgrades: [], recommendations: [], summary: { totalItems: 10, totalBuildings: 5, possibleUpgradeCount: 2, blockedUpgradeCount: 0, progressPercent: 85, remainingLevels: 5, remainingGoldCost: 1000, remainingElixirCost: 1000, remainingDarkElixirCost: 0, remainingBuildTimeHours: 100, builderUsagePercent: 90 } }, health: null, recommendations: [], activeQueue: [], goals: [], events: [], magicItems: [], resources: { gold: 0, elixir: 0, darkElixir: 0 }, storageCapacities: { gold: 1000, elixir: 1000, darkElixir: 1000 }, dailyIncome: { gold: 100, elixir: 100, darkElixir: 10 }, strategy: "balanced", simulationStartsAt: "2026-07-15T00:00:00.000Z", baseTotalDurationHours: 0, initialBuilderAvailabilityHours: [0,0,0,0,0], initialLaboratoryAvailabilityHours: 0 };
const health = (offense: number, heroes: number, completeness = 100): AccountHealthResult => ({ accountId: "a", score: 80, generalProgressScore: 80, balanceScore: 80, efficiencyScore: 90, strategyFitScore: 80, strategy: "balanced", rushRiskScore: 20, rushRiskLevel: "low", areas: ["offense","defense","heroes","laboratory","resources","goalAchievement"].map((id) => ({ id: id as AccountHealthResult["areas"][number]["id"], score: id === "offense" ? offense : id === "heroes" ? heroes : 85, progressScore: 85, entityCount: 1, measuredEntityCount: 1, dataComplete: true, weakestEntities: [] })), strongestArea: null, weakestArea: null, largestProgressGap: 10, improvements: [], missingData: [], dataCompletenessPercent: completeness, generatedAt: context.simulationStartsAt, calculationVersion: "health-v1.0.0" });
const entities = [{ id: "camp", name: "Armeelager", type: "building", category: "offense", currentLevel: 12, maxLevel: 12, remainingHours: 0 }, { id: "lab", name: "Labor", type: "building", category: "offense", currentLevel: 14, maxLevel: 14, remainingHours: 0 }];

test("Rathausmodell empfiehlt keinen Wechsel bei deutlicher Offensiv- und Heldenlücke", () => { const result = analyzeTownHallDecision({ context, strategy: "war", health: health(40, 35), entities, scheduledAt: "2026-08-01T00:00:00.000Z" }); assert.ok(["not_recommended","strategy_dependent"].includes(result.decision.recommendation)); assert.ok(result.decision.negatives.some((item) => item.code === "HERO_GAP")); });
test("Rathaus-Push wertet einen weit entwickelten Account ohne Maxing-Zwang positiv", () => { const result = analyzeTownHallDecision({ context, strategy: "town_hall_push", health: health(96, 80), entities, scheduledAt: "2026-08-01T00:00:00.000Z" }); assert.ok(["recommended","urgent"].includes(result.decision.recommendation)); assert.equal(result.variants.length, 3); assert.equal(result.variants[2].startsAt, context.simulationStartsAt); });
test("fehlende Daten reduzieren die Confidence", () => { const complete = analyzeTownHallDecision({ context, strategy: "balanced", health: health(90, 90, 100), entities, scheduledAt: null }); const incomplete = analyzeTownHallDecision({ context, strategy: "balanced", health: health(90, 90, 40), entities: [], scheduledAt: null }); assert.ok(incomplete.decision.confidence < complete.decision.confidence); });
