import type { BuilderSimulationResult } from "@/features/builder-simulation/builder-simulation.types";
import type { PlannerResult, ResourceSnapshot, UpgradeRecommendation } from "@/features/planner/planner.types";
import type { MagicInventoryItem, PlanningEvent } from "@/types/magicItems";
import type { PlanningProfile } from "@/types/planningProfile";
import type { UpgradeQueueItem } from "@/types/upgradeQueue";

export type AssistantQuestion = "next"|"town_hall"|"heroes_or_defense"|"delay"|"save_time"|"strategy"|"biggest_gap";
export type AssistantAnswer = { title:string; answer:string; evidence:string[]; action?:UpgradeRecommendation };
export type AssistantContext = { planner:PlannerResult|null; recommendations:UpgradeRecommendation[]; queue:UpgradeQueueItem[]; simulation:BuilderSimulationResult; resources:ResourceSnapshot; inventory:MagicInventoryItem[]; events:PlanningEvent[]; profile:PlanningProfile|null };
const fmt=(n:number)=>new Intl.NumberFormat("de-DE").format(Math.round(n));

export function answerAssistant(question:AssistantQuestion,c:AssistantContext):AssistantAnswer{
 const top=c.recommendations[0]; const longest=[...c.queue].filter(q=>q.status==="planned"||q.status==="active").sort((a,b)=>b.durationHours-a.durationHours)[0];
 if(question==="next")return top?{title:"Nächstes Upgrade",answer:`${top.name} auf Level ${top.nextLevel} ist aktuell die stärkste Empfehlung.`,evidence:[`Priorität 1 von ${c.recommendations.length} möglichen Upgrades`,`Dauer ${fmt(top.nextLevelTime.hours)} Stunden`,`Noch ${top.missingLevels} Level bis zum aktuellen Maximum`,top.recommendationReason],action:top}:{title:"Nächstes Upgrade",answer:"Aktuell wurde kein mögliches Upgrade gefunden.",evidence:["Alle verfügbaren Items sind maximal oder durch das Rathaus gesperrt."]};
 if(question==="town_hall"){const th=c.recommendations.find(r=>/rathaus|town hall/i.test(r.name));const progress=c.planner?.summary.progressPercent||0;return{title:"Rathaus-Entscheidung",answer:th&&progress>=75?`Der Rathaus-Schritt auf Level ${th.nextLevel} ist vertretbar.`:th?"Ich würde das Rathaus noch nicht vorziehen.":"Aktuell ist kein Rathaus-Upgrade als zulässiger nächster Schritt vorhanden.",evidence:[`Gesamtfortschritt ${fmt(progress)} %`,`${c.planner?.summary.remainingLevels||0} Restlevel`,th?`Rathaus steht auf Priorität ${c.recommendations.indexOf(th)+1}`:"Rathaus nicht in den möglichen Upgrades"],action:th};}
 if(question==="heroes_or_defense"){const hero=c.recommendations.find(r=>r.itemType==="hero");const defense=c.recommendations.find(r=>r.itemType==="building"&&/defen|verteid|kanone|turm|mörser|inferno|adler|monolith/i.test(`${r.category} ${r.name}`))||c.recommendations.find(r=>r.itemType==="building");const choice=!defense||hero&&c.recommendations.indexOf(hero)<c.recommendations.indexOf(defense)?hero:defense;return choice?{title:"Helden oder Verteidigung",answer:`${choice.itemType==="hero"?"Helden":"Verteidigung"} zuerst: ${choice.name} auf Level ${choice.nextLevel}.`,evidence:[hero?`Bester Held: Priorität ${c.recommendations.indexOf(hero)+1}`:"Kein Heldenupgrade verfügbar",defense?`Beste Verteidigung: Priorität ${c.recommendations.indexOf(defense)+1}`:"Keine Verteidigung verfügbar"],action:choice}:{title:"Helden oder Verteidigung",answer:"Keines der beiden Systeme hat aktuell ein mögliches Upgrade.",evidence:[]};}
 if(question==="delay"){const hours=c.simulation.totalDurationHours;const idle=c.simulation.idleTimeHours;return{title:"Warum verzögert sich der Plan?",answer:!c.queue.length?"Der Plan hat keine Queue und kann deshalb keinen Fortschritt simulieren.":idle>0?"Die Verzögerung kommt vor allem durch Bauarbeiter-Leerlauf und die aktuelle Queue-Verteilung.":"Die Queue ist ausgelastet; die verbleibende Dauer entsteht aus den eingeplanten Upgradezeiten.",evidence:[`${c.queue.length} Queue-Einträge`,`${fmt(hours)} Stunden Gesamtdauer`,`${fmt(idle)} Stunden berechneter Leerlauf`,`${c.events.filter(e=>e.enabled).length} aktive Event-Einstellungen`]};}
 if(question==="save_time"){const applicable=c.inventory.filter(i=>i.quantity>0&&longest&&i.appliesTo.includes(longest.itemType));return{title:"Wie kann ich Zeit sparen?",answer:longest?applicable.length?`Reserviere ${applicable[0].name} für ${longest.name}.`: `Das längste Upgrade ist ${longest.name}; dafür ist aktuell kein passendes Magic Item eingetragen.`:"Plane zuerst Upgrades in der Queue ein.",evidence:[longest?`${longest.name}: ${fmt(longest.durationHours)} Stunden`:"Queue leer",applicable.length?`${applicable[0].quantity}× ${applicable[0].name} vorhanden`:"Kein passender Gegenstand",`Aktiver Zeitrabatt bis ${Math.max(0,...c.events.filter(e=>e.enabled).map(e=>e.timeDiscountPercent))} %`]};}
 if(question==="strategy"){const style=c.profile?.playStyle||"ambitious";const labels={casual:"Gelegenheitsspieler",ambitious:"ambitionierter Spieler",hardcore:"Hardcore-Spieler"};return{title:"Passende Strategie",answer:`Dein Profil ist „${labels[style]}“. ${style==="casual"?"Eine ausgewogene Planung mit wenigen klaren Schritten passt am besten.":style==="hardcore"?"Eigene Gewichtungen, Szenarien und vollständige Queue-Kontrolle passen am besten.":"Strategie, Ziele, Queue und Ressourcenplanung sollten gemeinsam verwendet werden."}`,evidence:[`Gespeicherter Spielstil: ${labels[style]}`,`${c.recommendations.length} mögliche Upgrades`,`Builder-Auslastung über ${c.simulation.builderCount} Bauarbeiter`]};}
 const gap=[...(c.planner?.possibleUpgrades||[])].sort((a,b)=>b.missingLevels-a.missingLevels)[0];return gap?{title:"Größter Rückstand",answer:`${gap.name} hat mit ${gap.missingLevels} fehlenden Leveln den größten erkannten Rückstand.`,evidence:[`Aktuell Level ${gap.currentLevel}`,`Maximum Level ${gap.maxLevel}`,`${fmt(gap.remainingTime.hours)} Stunden verbleibende Upgradezeit`],action:c.recommendations.find(r=>r.itemId===gap.itemId)}:{title:"Größter Rückstand",answer:"Kein Rückstand gefunden.",evidence:["Alle verfügbaren Items sind maximal."]};
}
