"use client";

import type { AccountAnalysisAction, AccountAnalysisResult } from "@/features/account-analysis/account-analysis.types";

type Props = { analysis: AccountAnalysisResult; language: "de" | "en"; onApply: (action: AccountAnalysisAction) => void };
const style = { strength: "border-emerald-300/30 bg-emerald-300/10", balanced: "border-sky-300/20 bg-sky-300/5", weakness: "border-rose-300/30 bg-rose-300/10", unknown: "border-slate-600 bg-slate-900/60" };
export function DeepAccountAnalysis({ analysis, language, onApply }: Props) {
  const en = language === "en";
  return <section className="rounded-3xl border border-white/10 bg-white/5 p-5 md:p-7"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-violet-300">{en ? "Deep account analysis" : "Tiefgehende Accountanalyse"}</p><h2 className="mt-2 text-2xl font-bold">{en ? "Structural strengths and weaknesses" : "Strukturelle Stärken und Schwächen"}</h2><p className="mt-1 text-sm text-slate-400">{en ? "Every statement includes its measured basis; missing data is neutral." : "Jede Aussage nennt ihre Messgrundlage; fehlende Daten bleiben neutral."}</p></div>
    <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{analysis.findings.map((finding) => <article key={finding.id} className={`rounded-2xl border p-4 ${style[finding.status]}`}><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{en ? finding.statementEn : finding.statementDe}</h3><span className="text-sm font-black">{finding.score === null ? "?" : finding.score}</span></div><p className="mt-2 text-xs text-slate-300">{en ? finding.reasonEn : finding.reasonDe}</p>{finding.action ? <button type="button" onClick={() => onApply(finding.action as AccountAnalysisAction)} className="mt-3 rounded-xl bg-violet-200 px-3 py-2 text-xs font-bold text-slate-950">{en ? finding.action.en : finding.action.de}</button> : null}</article>)}</div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-emerald-300/10 p-4"><p className="text-xs text-slate-400">{en ? "Strongest measured area" : "Stärkster gemessener Bereich"}</p><b>{analysis.strongest ? (en ? analysis.strongest.statementEn : analysis.strongest.statementDe) : "–"}</b></div><div className="rounded-2xl bg-rose-300/10 p-4"><p className="text-xs text-slate-400">{en ? "Greatest measured gap" : "Größte gemessene Lücke"}</p><b>{analysis.weakest ? (en ? analysis.weakest.statementEn : analysis.weakest.statementDe) : "–"}</b></div></div><p className="mt-4 text-xs text-slate-500">{analysis.calculationVersion}</p></section>;
}
