"use client";

import { useMemo, useState } from "react";
import { filterTimeline } from "@/features/timeline/timeline.engine";
import type { TimelineEvent, TimelineLaneFilter, TimelineRange } from "@/features/timeline/timeline.types";

type Props = { items: TimelineEvent[]; language: "de" | "en"; onMoveUpgrade: (id: string, direction: "up" | "down") => void; onSetReminder: (item: TimelineEvent) => void; onCreateScenario: (item: TimelineEvent) => void; onViewFuture: (item: TimelineEvent) => void };
const laneColors: Record<TimelineEvent["lane"], string> = { builder: "border-amber-300/40 bg-amber-300/10", laboratory: "border-sky-300/40 bg-sky-300/10", pets: "border-lime-300/40 bg-lime-300/10", equipment: "border-cyan-300/40 bg-cyan-300/10", goals: "border-emerald-300/40 bg-emerald-300/10", events: "border-violet-300/40 bg-violet-300/10", account: "border-slate-400/40 bg-slate-400/10", resources: "border-orange-300/40 bg-orange-300/10" };

export function AccountTimeline({ items, language, onMoveUpgrade, onSetReminder, onCreateScenario, onViewFuture }: Props) {
  const en = language === "en"; const now = useMemo(() => new Date(), []);
  const [range, setRange] = useState<TimelineRange>("week"); const [lane, setLane] = useState<TimelineLaneFilter>("all"); const [mode, setMode] = useState<"list" | "calendar">("list"); const [selected, setSelected] = useState<TimelineEvent | null>(null);
  const visible = useMemo(() => filterTimeline(items, range, lane, now), [items, lane, now, range]);
  const groups = useMemo(() => [...visible.reduce<Map<string, TimelineEvent[]>>((result, item) => {
    const day = item.startsAt.slice(0, 10); result.set(day, [...(result.get(day) || []), item]); return result;
  }, new Map()).entries()], [visible]);
  const date = (iso: string, withTime = true) => new Intl.DateTimeFormat(en ? "en-GB" : "de-DE", withTime ? { dateStyle: "medium", timeStyle: "short" } : { dateStyle: "full" }).format(new Date(iso));
  const queueId = (item: TimelineEvent) => typeof item.metadata.queueItemId === "string" ? item.metadata.queueItemId : null;
  const card = (item: TimelineEvent) => { const past = new Date(item.startsAt) < now; return <button type="button" key={item.id} onClick={() => setSelected(item)} className={`w-full rounded-2xl border p-4 text-left transition hover:-translate-y-0.5 ${laneColors[item.lane]} ${past ? "opacity-60" : ""}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{item.type.replaceAll("_", " ")}{item.isEstimate ? " *" : ""}</p><h4 className="mt-1 font-bold text-white">{item.title}</h4></div><time className="shrink-0 text-xs text-slate-300">{date(item.startsAt)}</time></div><p className="mt-2 text-sm text-slate-300">{item.description}</p><span className="mt-2 inline-block text-[11px] text-slate-500">{past ? (en ? "Past" : "Vergangen") : (en ? "Future" : "Zukünftig")} · {item.lane}</span></button>; };
  return <section className="rounded-3xl border border-white/10 bg-white/5 p-5 md:p-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-sky-300">Timeline</p><h2 className="mt-2 text-2xl font-bold">{en ? "Past, plan and forecasts in one view" : "Vergangenheit, Plan und Prognosen in einer Ansicht"}</h2><p className="mt-1 text-sm text-slate-400">{en ? "Times use your local timezone. Asterisks mark simulated events." : "Zeiten verwenden deine lokale Zeitzone. Sterne markieren simulierte Ereignisse."}</p></div><div className="flex rounded-xl bg-slate-950 p-1"><button type="button" onClick={() => setMode("list")} className={`rounded-lg px-3 py-2 text-xs font-bold ${mode === "list" ? "bg-sky-300 text-slate-950" : ""}`}>{en ? "List" : "Liste"}</button><button type="button" onClick={() => setMode("calendar")} className={`rounded-lg px-3 py-2 text-xs font-bold ${mode === "calendar" ? "bg-sky-300 text-slate-950" : ""}`}>{en ? "Calendar" : "Kalender"}</button></div></div>
    <div className="mt-5 flex flex-wrap gap-2">{(["day","week","month","all"] as TimelineRange[]).map((value) => <button type="button" key={value} onClick={() => setRange(value)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${range === value ? "bg-white text-slate-950" : "bg-slate-900"}`}>{value === "day" ? (en ? "Day" : "Tag") : value === "week" ? (en ? "Week" : "Woche") : value === "month" ? (en ? "Month" : "Monat") : (en ? "Full plan" : "Gesamter Plan")}</button>)}</div>
    <div className="mt-2 flex flex-wrap gap-2">{(["all","builder","laboratory","pets","equipment","goals","events","resources","account"] as TimelineLaneFilter[]).map((value) => <button type="button" key={value} onClick={() => setLane(value)} className={`rounded-full px-3 py-1.5 text-xs ${lane === value ? "bg-sky-300 text-slate-950" : "bg-slate-950 text-slate-400"}`}>{value}</button>)}</div>
    {!visible.length ? <p className="mt-6 rounded-2xl bg-slate-950/60 p-6 text-center text-slate-500">{en ? "No events for this filter." : "Keine Ereignisse für diesen Filter."}</p> : mode === "list" ? <div className="mt-5 space-y-3">{visible.map(card)}</div> : <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{groups.map(([day, dayItems]) => <div key={day} className="rounded-2xl bg-slate-950/60 p-4"><h3 className="mb-3 font-bold">{date(`${day}T12:00:00`, false)}</h3><div className="space-y-2">{(dayItems || []).map(card)}</div></div>)}</div>}
    {selected ? <div className="sticky bottom-4 mt-5 rounded-2xl border border-sky-300/30 bg-slate-950 p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-sky-300">{selected.type} · {selected.sourceType}</p><h3 className="mt-1 text-xl font-bold">{selected.title}</h3><p className="mt-2 text-sm text-slate-300">{selected.description}</p><p className="mt-2 text-xs text-slate-500">{date(selected.startsAt)}{selected.endsAt ? ` – ${date(selected.endsAt)}` : ""}</p></div><button type="button" onClick={() => setSelected(null)} aria-label={en ? "Close" : "Schließen"}>×</button></div><div className="mt-4 flex flex-wrap gap-2">{queueId(selected) ? <><button type="button" onClick={() => onMoveUpgrade(queueId(selected) as string, "up")} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">↑ {en ? "Move" : "Verschieben"}</button><button type="button" onClick={() => onMoveUpgrade(queueId(selected) as string, "down")} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">↓ {en ? "Move" : "Verschieben"}</button><button type="button" onClick={() => document.getElementById("upgrade-queue")?.scrollIntoView({ behavior: "smooth" })} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold">{en ? "Edit queue entry" : "Queue-Eintrag bearbeiten"}</button></> : null}<button type="button" onClick={() => onSetReminder(selected)} className="rounded-xl border border-violet-300/30 px-3 py-2 text-xs font-bold text-violet-200">{en ? "Set reminder" : "Erinnerung setzen"}</button><button type="button" onClick={() => onCreateScenario(selected)} className="rounded-xl border border-amber-300/30 px-3 py-2 text-xs font-bold text-amber-200">{en ? "Scenario from here" : "Szenario ab hier"}</button><button type="button" onClick={() => onViewFuture(selected)} className="rounded-xl border border-emerald-300/30 px-3 py-2 text-xs font-bold text-emerald-200">{en ? "Future account" : "Zukünftiger Account"}</button></div></div> : null}
  </section>;
}
